/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.2.24
 * on Mon Aug 21 15:59:03 CST 2023. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_Swc1_Velocity.h>

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) task_10ms_cycli (void)
{
  uint8 arg_IWrite_data = 0U;
  P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef;
  impl_Spd4_2 ret_IRead;
  uint8 ret_IRead_0;
  Std_ReturnType ret_Call;

  Rte_IWrite_task_10ms_cycli_pp_Unit_1_VehSpdUnitForUseInt(arg_IWrite_data);
  ret_IWriteRef = Rte_IWriteRef_task_10ms_cycli_pp_Unit_1_VehSpdUnitForUseInt();
  ret_IRead = Rte_IRead_task_10ms_cycli_rp_SpeedIn_DispSpdSetForLgtCtrl();
  ret_IRead_0 = Rte_IRead_task_10ms_cycli_rp_Unit_1_VehSpdUnitForUseInt();
  ret_Call = Rte_Call_rp_cs_Inform_Info_Oper();

} /* FUNC(void, RTE_CODE) task_10ms_cycli (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
