/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.2.24
 * on Mon Aug 21 15:59:03 CST 2023. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_Swc2_Odometer.h>

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) Swc2_Runable (void)
{
  uint8 ret_IRead;
  uint8 Speed_unit;
  static uint32 Swc_Odemeter_Disp;
  static uint32 Swc_Odometer;

  P2CONST(Msm_stVehicleModeInfoToApp, AUTOMATIC, RTE_APPL_DATA) ret_IRead_0;                                                                                             


  ret_IRead = Rte_IRead_Swc2_Runable_rp_Unit2_VehSpdUnitForUseInt();
  ret_IRead_0 = Rte_IRead_Swc2_Runable_rp_Usagemode_stVehicleModeInfo();



  P2CONST(Msm_stVehicleModeInfoToApp, AUTOMATIC, RTE_APPL_DATA) usagemode;
  Speed_unit = Rte_IRead_Swc2_Runable_rp_Unit2_VehSpdUnitForUseInt();//Speed_unit
  usagemode = Rte_IRead_Swc2_Runable_rp_Usagemode_stVehicleModeInfo();// usagemode


  /*
  SWC2 (Odometer):
  1).  SWC2负责累加公里数, 精度为0.1km/0.1mile, 并将结果放到一个uint32的变量中，不需要存NVM
  2).  基于SWC1传递过来的单位，进行里程单位转换0表示km, 1表示mile

  3).  对于总里程而言，只有在usagemode = driving(isVehModMngtGlbSafe1UsgModSts = 13)的情况下，才进行累加。usagemode条件不满足时停止累计。
  */

  if (ret_IRead_0 == 13)
  {
      Swc_Odometer = Swc_Odometer + 10;
      if (Speed_unit == 1)
      {
          Swc_Odemeter_Disp = Swc_Odometer * 0.006214;
      }
      if (Speed_unit == 0)
      {
          Swc_Odemeter_Disp = Swc_Odometer * 0.01;
      }
      else
      {

      }
  }
  else
  {

  }



} /* FUNC(void, RTE_CODE) Swc2_Runable (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
